#!/bin/sh
# Keeps stage1 sources inside the bootstrap subset. Rules: docs/BOOTSTRAP.md.
set -u

fail=0

report() {
	printf '\033[31m%s\033[0m %s\n' "$1" "$2"
	fail=1
}

# Drop comments and string bodies so diagnostic text is not mistaken for code.
strip() {
	sed -e 's|//.*||' -e 's|"[^"]*"|""|g' "$1"
}

# The subset binds whatever stage1 is built from: srcql/ plus the std modules it
# imports, directly or through another. The rest of std/ is compiled by stage1
# itself and may use the whole language.
#
# srcql/interp.qela is the one exception in srcql/: tools/bootstrap.sh drops it
# from the stage0 step with -D BOOTSTRAP=1, so no stage0 ever sees it and it may
# use the whole language. Its imports must not drag std modules into the subset
# either, so it is filtered out here and skipped by every check below.
boot_std=$(grep -ho 'import "\.\./std/[A-Za-z_0-9]*\.qela"' \
	$(ls srcql/*.qela | grep -v '^srcql/interp\.qela$') |
	sed 's|.*/std/||;s|\.qela"||' | sort -u | tr '\n' ' ')
changed=1
while [ "$changed" = 1 ]; do
	changed=0
	for m in $boot_std; do
		deps=$(grep -ho 'import "[A-Za-z_0-9]*\.qela"' "std/$m.qela" 2>/dev/null |
			sed 's|import "||;s|\.qela"||')
		for d in $deps; do
			case " $boot_std " in
			*" $d "*) ;;
			*) boot_std="$boot_std $d "; changed=1 ;;
			esac
		done
	done
done

in_bootstrap() {
	case "$1" in
	srcql/interp.qela) return 1 ;;
	srcql/*) return 0 ;;
	esac
	case " $boot_std " in
	*" $(basename "$1" .qela) "*) return 0 ;;
	esac
	return 1
}

for f in srcql/*.qela std/*.qela; do
	[ -e "$f" ] || continue

	# Generated by tools/genblob.py: all of std/ as string literals, escaped
	# quotes and all. strip()'s naive sed can't parse those reliably, so a
	# keyword surviving or not survives by luck of quote-pairing, not by
	# being real stage1 code. Skip it like std/* is skipped below.
	if in_bootstrap "$f" && [ "$f" != "srcql/std_blob.qela" ]; then
		for kw in comptime match defer; do
			if strip "$f" | grep -qw "$kw"; then
				report "$f:" "uses '$kw', forbidden in stage1 sources"
			fi
		done
	fi

	case "$f" in
	std/*) ;;
	# Generated by tools/genblob.py: all of std/ as string literals, including
	# std/sys.qela's own already-wrapped syscalls. Not stage1 code calling
	# them directly, so it is exempt like std/* is.
	srcql/std_blob.qela) ;;
	# Stage1-only, so asm and assert/panic (both stage0 limitations) are its
	# to use. The syscall rule is about layering rather than stage0, so it
	# still applies.
	srcql/interp.qela)
		if strip "$f" | grep -qE '(^|[^_[:alnum:]])syscall *\('; then
			report "$f:" "raw syscall, wrap it in std/sys.qela"
		fi
		;;
	*)
		if strip "$f" | grep -qE '(^|[^_[:alnum:]])syscall *\('; then
			report "$f:" "raw syscall, wrap it in std/sys.qela"
		fi
		if strip "$f" | grep -qE '(^|[^_[:alnum:]])asm *\('; then
			report "$f:" "asm(...) is not allowed in stage1's own sources"
		fi
		if strip "$f" | grep -qE '(^|[^_[:alnum:]])assert *\(|(^|[^_[:alnum:]])panic *\('; then
			report "$f:" "assert/panic is not allowed in stage1's own sources"
		fi
		;;
	esac

	strip "$f" | grep -o '^fn [a-zA-Z_0-9]*([^)]*)' | while read -r sig; do
		args=$(printf '%s' "$sig" | sed 's|^fn [a-zA-Z_0-9]*(||;s|)$||')
		[ -z "$args" ] && continue
		n=$(printf '%s' "$args" | tr ',' '\n' | grep -c .)
		[ "$n" -gt 6 ] && printf '\033[31m%s:\033[0m %s parameters in %s (max 6)\n' \
			"$f" "$n" "$sig"
	done
done

[ "$fail" -eq 0 ] && printf 'ok: stage1 sources are within the bootstrap subset\n'
exit "$fail"
