#!/usr/bin/env python3
"""Bakes std/*.qela into srcql/std_blob.qela so the compiler carries the
standard library inside its own binary.

The sources are LZSS-compressed here and unpacked by srcql/blob.qela at
runtime: only the decoder ships, the compressor stays in this script. The
format is one flag byte per eight items, LSB first; a set bit is a literal
byte, a clear bit is a two-byte back reference, big-endian, holding a
12-bit distance (minus one) and a 4-bit length (minus three).

The module directory is a table, not a chain of comparisons: the names go
to srcql/std.names, NUL-terminated in module order, and one (u32 offset,
u16 length) little-endian record per module to srcql/std.index. All three
files are embedded with $bytes; srcql/blob.qela reads them.

Modules are emitted in sorted order: the blob feeds compiler output, so its
layout has to be reproducible (see docs/BOOTSTRAP.md, "Determinism").
"""
import os
import struct
import sys

SRC_DIR = "std"
OUT = "srcql/std_blob.qela"
BLOB = "srcql/std.lzss"
NAMES_OUT = "srcql/std.names"
INDEX_OUT = "srcql/std.index"

WINDOW = 4096
MIN_MATCH = 3
MAX_MATCH = 18


def compress(data: bytes) -> bytes:
    out = bytearray()
    items = bytearray()
    flags = 0
    nflags = 0
    heads: dict[bytes, list[int]] = {}
    i = 0
    n = len(data)
    while i < n:
        best_len = 0
        best_dist = 0
        if i + MIN_MATCH <= n:
            key = data[i:i + MIN_MATCH]
            for pos in reversed(heads.get(key, [])):
                dist = i - pos
                if dist > WINDOW:
                    break
                ln = MIN_MATCH
                limit = min(MAX_MATCH, n - i)
                while ln < limit and data[pos + ln] == data[i + ln]:
                    ln += 1
                if ln > best_len:
                    best_len = ln
                    best_dist = dist
                    if ln == MAX_MATCH:
                        break
        if best_len >= MIN_MATCH:
            code = ((best_dist - 1) << 4) | (best_len - MIN_MATCH)
            items.append((code >> 8) & 0xFF)
            items.append(code & 0xFF)
            step = best_len
        else:
            flags |= 1 << nflags
            items.append(data[i])
            step = 1
        nflags += 1
        if nflags == 8:
            out.append(flags)
            out += items
            items = bytearray()
            flags = 0
            nflags = 0
        for k in range(step):
            p = i + k
            if p + MIN_MATCH <= n:
                heads.setdefault(data[p:p + MIN_MATCH], []).append(p)
        i += step
    if nflags:
        out.append(flags)
        out += items
    return bytes(out)


def decompress(src: bytes, out_len: int) -> bytes:
    out = bytearray()
    i = 0
    while len(out) < out_len:
        flags = src[i]
        i += 1
        for bit in range(8):
            if len(out) >= out_len:
                break
            if flags & (1 << bit):
                out.append(src[i])
                i += 1
            else:
                code = (src[i] << 8) | src[i + 1]
                i += 2
                dist = (code >> 4) + 1
                ln = (code & 15) + MIN_MATCH
                start = len(out) - dist
                for k in range(ln):
                    out.append(out[start + k])
    return bytes(out)


def main() -> int:
    names = sorted(n for n in os.listdir(SRC_DIR) if n.endswith(".qela"))
    if not names:
        print("no modules found in std/", file=sys.stderr)
        return 1

    bodies = []
    for name in names:
        with open(os.path.join(SRC_DIR, name), "rb") as f:
            body = f.read()
        bodies.append(body)

    joined = b"".join(bodies)
    packed = compress(joined)
    if decompress(packed, len(joined)) != joined:
        print("error: the packed blob does not round-trip", file=sys.stderr)
        return 1

    with open(BLOB, "wb") as f:
        f.write(packed)

    # The directory: names NUL-terminated in module order (the concatenation
    # order, so entry i is the i-th NUL-delimited piece), and offsets and
    # lengths little-endian. Every target is little-endian, and blob.qela
    # assembles the two words by hand, so the file is a plain dump.
    names_blob = bytearray()
    for name in names:
        names_blob += b"std/" + name.encode() + b"\x00"
    index = bytearray()
    off = 0
    for body in bodies:
        index += struct.pack("<IH", off, len(body))
        off += len(body)
    with open(NAMES_OUT, "wb") as f:
        f.write(names_blob)
    with open(INDEX_OUT, "wb") as f:
        f.write(index)

    lines = [
        "// Generated by tools/genblob.py. Do not edit.",
        "// The standard library: LZSS-packed into srcql/std.lzss, with the",
        "// module directory in srcql/std.names and srcql/std.index. All three",
        "// are embedded with $bytes and read by srcql/blob.qela. stage0 has no",
        "// $bytes, and S1a never needs them (it compiles stage1 from the",
        "// source tree), so the bootstrap build carries empty ones.",
        "",
        '$if (BOOTSTRAP != "1") {',
        'fn std_blob_data() str { return $bytes("std.lzss"); }',
        'fn std_blob_names() str { return $bytes("std.names"); }',
        'fn std_blob_index() str { return $bytes("std.index"); }',
        "} $else {",
        'fn std_blob_data() str { return ""; }',
        'fn std_blob_names() str { return ""; }',
        'fn std_blob_index() str { return ""; }',
        "}",
        "",
        f"fn std_blob_count() int {{ return {len(names)}; }}",
        "",
        f"fn std_blob_total() i64 {{ return {len(joined)}; }}",
        "",
    ]

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    ratio = len(packed) * 100.0 / len(joined)
    print(
        f"{OUT}: {len(names)} modules, {len(joined)} bytes of source, "
        f"{BLOB} {len(packed)} packed ({ratio:.1f}%), "
        f"{NAMES_OUT} + {INDEX_OUT} {len(names_blob) + len(index)} of directory"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
