#!/usr/bin/env python3
"""Bakes std/*.qela into srcql/std_blob.qela so the compiler carries the
standard library inside its own binary.

Modules are emitted in sorted order: the blob feeds compiler output, so its
layout has to be reproducible (see docs/BOOTSTRAP.md, "Determinism").
"""
import os
import sys

SRC_DIR = "std"
OUT = "srcql/std_blob.qela"


def escape(text: str) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\0":
            out.append("\\0")
        else:
            out.append(ch)
    return "".join(out)


def main() -> int:
    names = sorted(n for n in os.listdir(SRC_DIR) if n.endswith(".qela"))
    if not names:
        print("no modules found in std/", file=sys.stderr)
        return 1

    lines = [
        "// Generated by tools/genblob.py. Do not edit.",
        "// The standard library, carried inside the compiler binary.",
        "",
        f"fn std_blob_count() int {{ return {len(names)}; }}",
        "",
        "fn std_blob_name(i int) str {",
    ]
    for idx, name in enumerate(names):
        lines.append(f'\tif (i == {idx}) {{ return "std/{name}"; }}')
    lines += ['\treturn "";', "}", "", "fn std_blob_src(i int) str {"]

    total = 0
    for idx, name in enumerate(names):
        with open(os.path.join(SRC_DIR, name), encoding="utf-8") as f:
            body = f.read()
        if "${" in body:
            print(
                f"error: std/{name} contains '$' + '{{', which the compiler's "
                "lexer would read as the start of a string interpolation "
                "inside the blob literal; rephrase the source",
                file=sys.stderr,
            )
            return 1
        total += len(body)
        lines.append(f'\tif (i == {idx}) {{ return "{escape(body)}"; }}')
    lines += ['\treturn "";', "}", ""]

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"{OUT}: {len(names)} modules, {total} bytes of source")
    return 0


if __name__ == "__main__":
    sys.exit(main())
